name: MagGeoEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pandas
  - notebook
  - geopandas
  - matplotlib
  - xarray
  - cartopy
  - geoplot
  - gdal
  - shapely
  - numpy
  - geojson
  - requests
  - cdflib
  - Jinja2
  - pytables
  - tqdm
  - scipy
  - cython
  - h5py
  - pip:
    - cdflib
    - hdf5storage
    - viresclient
    - chaosmagpy