# Python environment for MagGeo
name: MagGeoEnv_2

channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyter
  - jupyterlab
  - numpy
  - scipy
  - pandas
  - xarray
  - netcdf4
  - matplotlib
  - jinja2
  - tqdm
  - click
  - pyyaml
  - ipywidgets
  - cartopy
  - geopandas

  - pip:
      - markupsafe
      - pooch
      - viresclient
      - chaosmagpy