site_name: MagGeo
site_description: Data Fusion tool to annotate GPS trajectories with Geomagnetic data from Swarm satellites
repo_url: https://github.com/MagGeo/MagGeo

theme:
  name: material
  palette:
    primary: blue
    accent: amber
  features:
    - navigation.tabs
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - User Guide:
    - Basic Usage: user-guide/basic-usage.md
    - Swarm Data Manager: user-guide/swarm-data-manager.md
    - Parallel Processing: user-guide/parallel-processing.md
    - Command Line Interface: user-guide/cli.md
    - Configuration: user-guide/configuration.md
  - API Reference:
    - Overview: api/index.md
    - Core Functions: api/core.md
    - SwarmDataManager: api/swarm_data_manager.md
    #- Interpolation: api/interpolation.md
    #- CHAOS Model: api/chaos.md
    #- Date Utilities: api/date_utils.md
    - Parallel Processing: api/parallel_processing.md
    - Geomagnetic Indices: api/indices.md
  - Examples:
    - Basic Examples: examples/basic.md
    - Advanced Workflows: examples/advanced.md
    #- Jupyter Notebooks: examples/notebooks.md
    #- Research Use Cases: examples/research.md
  #- Development:
    #- Contributing: development/contributing.md
    #- Testing: development/testing.md
    #- Release Process: development/release.md
  - About:
    - Changelog: about/changelog.md
    - Citation: about/citation.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed

#extra_css:
#  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js