project:
  type: website

website:
  title: " MagGeo: Data fusion tool to combine magnetic data with GPS trajectories"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Using it"
        contents:
          - installation.qmd
          - using_maggeo.qmd
          - troubleshooting.qmd
      - section: "Notebooks"
        contents:
          - sequential.qmd
          - parallel.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    