project:
  type: website

website:
  favicon: /images/path1806.png
  title: " MagGeo: Data fusion tool to combine magnetic data with GPS trajectories"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "How to use it"
        contents:
          - installation.qmd
          - using_maggeo.qmd
          - data_requeriments.qmd
          - troubleshooting.qmd
      - section: "The science behind" 
        contents: 
          - intro.qmd
          - relevant_concepts.qmd
          - calculation_mag_components.qmd
          - how_does_it_works.qmd
      - section: "Notebooks"
        contents:
          - SequentialMode.ipynb
          - ParallelMode.ipynb
format:
  html:
    theme: cosmo
    css: styles.css
    